### ISSUE TITLE
"end of file reached" issue

### ISSUE THREAD

**Issue by pfcfernandez** [dougal/acts_as_indexed#38]
Hello I started to notice this last night.. and cant seem to be able to log in now..

from rails production log:

Started POST "/refinery/users/login?fromsite=1" for 204.16.153.250 at 2012-11-15 13:22:04 -0800
Completed 500 Internal Server Error in 10786ms

EOFError (end of file reached):
  app/controllers/refinery/sessions_controller.rb:22:in `create'

from my log server:
From: cms
Date: 2012-11-15 13:22:12 -0800
Severity: Debug
Facility: graylog2_exceptions
File: /home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:87
Full message:
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:87:in `load'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:87:in`block (3 levels) in operate'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:86:in `open'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:86:in`open'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:86:in `block (2 levels) in operate'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:180:in`block in lock_file'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:177:in `open'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:177:in`open'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:177:in `lock_file'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:83:in`block in operate'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:80:in `each'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:80:in`operate'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/storage.rb:30:in `remove'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/search_index.rb:50:in`remove_record'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/search_index.rb:54:in `update_record'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/class_methods.rb:87:in`index_update'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/acts_as_indexed-0.7.8/lib/acts_as_indexed/instance_methods.rb:28:in `update_index'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:407:in`_run__243750755060159493__update__692564817154729579__callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:385:in`_run_update_callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/callbacks.rb:272:in`update'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/persistence.rb:347:in `create_or_update'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/callbacks.rb:264:in`block in create_or_update'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:425:in `_run__243750755060159493__save__692564817154729579__callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in`__run_callback'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:81:in`run_callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/callbacks.rb:264:in `create_or_update'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/persistence.rb:84:in`save'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/validations.rb:50:in `save'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/attribute_methods/dirty.rb:22:in`save'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/transactions.rb:241:in `block (2 levels) in save'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/transactions.rb:295:in`block in with_transaction_returning_status'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/transactions.rb:208:in`transaction'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/transactions.rb:241:in`block in save'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/transactions.rb:252:in `rollback_active_record_state!'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/transactions.rb:240:in`save'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/devise-2.0.4/lib/devise/models/trackable.rb:26:in `update_tracked_fields!'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/devise-2.0.4/lib/devise/hooks/trackable.rb:7:in`block in <top (required)>'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/warden-1.1.1/lib/warden/hooks.rb:14:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/warden-1.1.1/lib/warden/hooks.rb:14:in`block in _run_callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/warden-1.1.1/lib/warden/hooks.rb:9:in `each'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/warden-1.1.1/lib/warden/hooks.rb:9:in`_run_callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/warden-1.1.1/lib/warden/manager.rb:53:in `_run_callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/warden-1.1.1/lib/warden/proxy.rb:165:in`set_user'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/devise-2.0.4/lib/devise/controllers/helpers.rb:124:in `sign_in'
/var/www/playfirst_cms/app/controllers/refinery/sessions_controller.rb:22:in`create'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/abstract_controller/base.rb:167:in`process_action'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/abstract_controller/callbacks.rb:18:in`block in process_action'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:491:in `_run__4547756213461430065__process_action__3619842155605981004__callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in`__run_callback'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:81:in`run_callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/abstract_controller/callbacks.rb:17:in `process_action'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/rescue.rb:29:in`process_action'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/notifications.rb:123:in`block in instrument'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/notifications.rb:123:in`instrument'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/abstract_controller/base.rb:121:in`process'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/abstract_controller/rendering.rb:45:in `process'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal.rb:203:in`dispatch'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_controller/metal.rb:246:in`block in action'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:73:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:36:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/routing/mapper.rb:42:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/journey-1.0.4/lib/journey/router.rb:56:in`each'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:600:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.8/lib/rails/engine.rb:479:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in`method_missing'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/journey-1.0.4/lib/journey/router.rb:56:in`each'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:600:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/graylog2_exceptions-1.3.0/lib/graylog2_exceptions.rb:30:in `_call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/graylog2_exceptions-1.3.0/lib/graylog2_exceptions.rb:24:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/warden-1.1.1/lib/warden/manager.rb:35:in `block in call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/warden-1.1.1/lib/warden/manager.rb:34:in`catch'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/warden-1.1.1/lib/warden/manager.rb:34:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/etag.rb:23:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/conditionalget.rb:35:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/head.rb:14:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/params_parser.rb:21:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/flash.rb:242:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in`context'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/cookies.rb:339:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/dragonfly-0.9.12/lib/dragonfly/cookie_monster.rb:9:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/query_cache.rb:64:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in `_run__2493813651070428835__call__692564817154729579__callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in`__run_callback'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:81:in`run_callbacks'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/dragonfly-0.9.12/lib/dragonfly/middleware.rb:13:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/dragonfly-0.9.12/lib/dragonfly/middleware.rb:13:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in`forward'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in`invalidate'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in`pass'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in`call!'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.8/lib/rails/rack/logger.rb:26:in `call_app'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.8/lib/rails/rack/logger.rb:16:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/actionpack-3.2.8/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/runtime.rb:17:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-1.4.1/lib/rack/lock.rb:15:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in`pass'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in`call!'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.8/lib/rails/engine.rb:479:in`call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.8/lib/rails/application.rb:223:in `call'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in`method_missing'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/abstract_request_handler.rb:516:in`accept_and_process_next_request'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/rack/application_spawner.rb:206:in`start_request_handler'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/utils.rb:470:in`safe_fork'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:180:in`start'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/rack/application_spawner.rb:129:in `start'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:253:in`block (2 levels) in spawn_rack_application'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:246:in`block in spawn_rack_application'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
<internal:prelude>:10:in`synchronize'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:244:in`spawn_rack_application'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/spawn_manager.rb:275:in`handle_spawn_application'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
/home/playfirst/.rvm/gems/ruby-1.9.3-p286/gems/passenger-3.0.18/helper-scripts/passenger-spawn-server:99:in `<main>'

**Comment by ryankopf** [comment]
Going to assume this is fixed or no longer relevant, as it's been 10 years.
