### ISSUE TITLE
Errno::ENOENT No such (No such file or directory ...)

### ISSUE THREAD

**Issue by davidkovaccs** [dougal/acts_as_indexed#47]
We are using refinery and having similar issues lately when creating objects. Our collected_activityitem model has: acts_as_indexed [:name]
We used acts_as_indexed 0.7.8 then switched to 0.8.3 hoping that it will solve this problem but not. I'm not totally sure that the problem is with acts_as_indexed but it seems to me.

What can be the problem?

Thanks, David

Stack on error:

Errno::ENOENT (No such file or directory - /home/toplamax/toplamax_web/tmp/index/production/refinery/collected_activityitems/collected_activityitem/117_51_48.ind.tmp or /home/toplamax/toplamax_web/tmp/index/production/refinery/collected_activityitems/collected_activityitem/117_51_48.ind):
  backports (3.3.0) lib/backports/tools.rb:143:in `rename_without_potential_path_argument'
  backports (3.3.0) lib/backports/tools.rb:143:in`rename'
  /usr/lib/ruby/1.8/fileutils.rb:506:in `mv'
  /usr/lib/ruby/1.8/fileutils.rb:1397:in`fu_each_src_dest'
  /usr/lib/ruby/1.8/fileutils.rb:1413:in `fu_each_src_dest0'
  /usr/lib/ruby/1.8/fileutils.rb:1395:in`fu_each_src_dest'
  /usr/lib/ruby/1.8/fileutils.rb:495:in `mv'
  acts_as_indexed (0.8.3) lib/acts_as_indexed/storage.rb:167:in`write_file'
  acts_as_indexed (0.8.3) lib/acts_as_indexed/storage.rb:93:in `operate'
  acts_as_indexed (0.8.3) lib/acts_as_indexed/storage.rb:182:in`lock_file'
  backports (3.3.0) lib/backports/tools.rb:143:in `open_without_potential_path_argument'
  backports (3.3.0) lib/backports/tools.rb:143:in`open'
  /usr/lib/ruby/1.8/pathname.rb:812:in `open'
  acts_as_indexed (0.8.3) lib/acts_as_indexed/storage.rb:179:in`lock_file'
  acts_as_indexed (0.8.3) lib/acts_as_indexed/storage.rb:175:in `synchronize'
  acts_as_indexed (0.8.3) lib/acts_as_indexed/storage.rb:175:in`lock_file'
  acts_as_indexed (0.8.3) lib/acts_as_indexed/storage.rb:81:in `operate'
  activesupport (3.2.7) lib/active_support/ordered_hash.rb:162:in`each'
  activesupport (3.2.7) lib/active_support/ordered_hash.rb:162:in `each'
  acts_as_indexed (0.8.3) lib/acts_as_indexed/storage.rb:78:in`operate'
  acts_as_indexed (0.8.3) lib/acts_as_indexed/storage.rb:21:in `add'
  acts_as_indexed (0.8.3) lib/acts_as_indexed/search_index.rb:23:in`add_record'
  acts_as_indexed (0.8.3) lib/acts_as_indexed/class_methods.rb:59:in `index_add'
  acts_as_indexed (0.8.3) lib/acts_as_indexed/instance_methods.rb:11:in`add_to_index'
  activesupport (3.2.7) lib/active_support/callbacks.rb:405:in `_run__1452809277__create__4__callbacks'
  activesupport (3.2.7) lib/active_support/callbacks.rb:405:in`send'
  activesupport (3.2.7) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.7) lib/active_support/callbacks.rb:385:in`_run_create_callbacks'
  activesupport (3.2.7) lib/active_support/callbacks.rb:81:in `send'
  activesupport (3.2.7) lib/active_support/callbacks.rb:81:in`run_callbacks'
  activerecord (3.2.7) lib/active_record/callbacks.rb:268:in `create'
  activerecord (3.2.7) lib/active_record/persistence.rb:348:in`create_or_update'
  activerecord (3.2.7) lib/active_record/callbacks.rb:264:in `create_or_update'
activesupport (3.2.7) lib/active_support/callbacks.rb:436:in`_run__1452809277__save__4__callbacks'
  activesupport (3.2.7) lib/active_support/callbacks.rb:405:in `send'
  activesupport (3.2.7) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.7) lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
  activesupport (3.2.7) lib/active_support/callbacks.rb:81:in`send'
  activesupport (3.2.7) lib/active_support/callbacks.rb:81:in `run_callbacks'
  activerecord (3.2.7) lib/active_record/callbacks.rb:264:in`create_or_update'
  activerecord (3.2.7) lib/active_record/persistence.rb:84:in `save'
  activerecord (3.2.7) lib/active_record/validations.rb:50:in`save'
  activerecord (3.2.7) lib/active_record/attribute_methods/dirty.rb:22:in `save'
  activerecord (3.2.7) lib/active_record/transactions.rb:241:in`save'
  activerecord (3.2.7) lib/active_record/transactions.rb:295:in `with_transaction_returning_status'
  activerecord (3.2.7) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in`transaction'
  activerecord (3.2.7) lib/active_record/transactions.rb:208:in `transaction_without_trace_ActiveRecord_self_name_transaction'
  newrelic_rpm (3.6.3.104) lib/new_relic/agent/method_tracer.rb:523:in`transaction'
  newrelic_rpm (3.6.3.104) lib/new_relic/agent/method_tracer.rb:273:in `trace_execution_scoped'
  newrelic_rpm (3.6.3.104) lib/new_relic/agent/method_tracer.rb:518:in`transaction'
  activerecord (3.2.7) lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
  activerecord (3.2.7) lib/active_record/transactions.rb:241:in`save'
  activerecord (3.2.7) lib/active_record/transactions.rb:252:in `rollback_active_record_state!'
  activerecord (3.2.7) lib/active_record/transactions.rb:240:in`save'
  activerecord (3.2.7) lib/active_record/persistence.rb:45:in `create'
  vendor/extensions/collected_activityitems/app/models/refinery/collected_activityitems/collected_activityitem.rb:130:in`create_record'
  vendor/extensions/synchronizations/app/controllers/refinery/synchronizations/synchronizations_controller.rb:562:in `create_record'
  actionpack (3.2.7) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
  actionpack (3.2.7) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.7) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.7) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.7) lib/abstract_controller/callbacks.rb:18:in`process_action'
  activesupport (3.2.7) lib/active_support/callbacks.rb:447:in `_run__378300131__process_action__209150944__callbacks'
  activesupport (3.2.7) lib/active_support/callbacks.rb:405:in`send'
  activesupport (3.2.7) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.7) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
  activesupport (3.2.7) lib/active_support/callbacks.rb:81:in `send'
  activesupport (3.2.7) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.7) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.7) lib/action_controller/metal/instrumentation.rb:30:in`process_action'
  activesupport (3.2.7) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.7) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.7) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.7) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.7) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.7) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  newrelic_rpm (3.6.3.104) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:38:in `process_action'
  newrelic_rpm (3.6.3.104) lib/new_relic/agent/instrumentation/controller_instrumentation.rb:318:in`perform_action_with_newrelic_trace'
  newrelic_rpm (3.6.3.104) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:37:in `process_action'
  actionpack (3.2.7) lib/abstract_controller/base.rb:121:in`process'
  actionpack (3.2.7) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.7) lib/action_controller/metal.rb:203:in`dispatch'
  actionpack (3.2.7) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.7) lib/action_controller/metal.rb:246:in`action'
  actionpack (3.2.7) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.7) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
  actionpack (3.2.7) lib/action_dispatch/routing/route_set.rb:36:in `call'
  actionpack (3.2.7) lib/action_dispatch/routing/mapper.rb:42:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `call'
  journey (1.0.4) lib/journey/router.rb:56:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.7) lib/action_dispatch/routing/route_set.rb:600:in`call'
  railties (3.2.7) lib/rails/engine.rb:479:in `call'
  railties (3.2.7) lib/rails/railtie/configurable.rb:30:in`send'
  railties (3.2.7) lib/rails/railtie/configurable.rb:30:in `method_missing'
  journey (1.0.4) lib/journey/router.rb:68:in`call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in`call'
  actionpack (3.2.7) lib/action_dispatch/routing/route_set.rb:600:in `call'
  newrelic_rpm (3.6.3.104) lib/new_relic/rack/error_collector.rb:12:in`call'
  newrelic_rpm (3.6.3.104) lib/new_relic/rack/agent_hooks.rb:22:in `call'
  newrelic_rpm (3.6.3.104) lib/new_relic/rack/browser_monitoring.rb:16:in`call'
  warden (1.2.1) lib/warden/manager.rb:35:in `call'
  warden (1.2.1) lib/warden/manager.rb:34:in`catch'
  warden (1.2.1) lib/warden/manager.rb:34:in `call'
.....

**Comment by ryankopf** [comment]
Going to assume this was version specific to an old version and is no longer relevant. If you are having any further issues, please open a new issue.
