### ISSUE TITLE
Rails 4 Deprecation Warnings

### ISSUE THREAD

**Issue by steelheaddigital** [dougal/acts_as_indexed#54]
Deprecation warnings with Rails 4.0.8 and ActiveRecord 4.0.8 when using find_with_index.

**This code:**
`my_search_results = Post.find_with_index('my search query')`

**will cause the following deprecation warnings:**

DEPRECATION WARNING: ActiveRecord::Base#with_scope and #with_exclusive_scope are deprecated. Please use ActiveRecord::Relation#scoping instead. (You can use #merge to merge multiple scopes together.)

DEPRECATION WARNING: Calling #find(:all) is deprecated. Please call #all directly instead. You have also used finder options. These are also deprecated. Please build a scope instead of using finder options

DEPRECATION WARNING: Relation#all is deprecated. If you want to eager-load a relation, you can call #load (e.g. `Post.where(published: true).load`). If you want to get an array of records from a relation, you can call #to_a (e.g. `Post.where(published: true).to_a`)

**Comment by mameier** [comment]
Hi dugal,
could you possibly include the patch of recotan (https://github.com/rekotan/acts_as_indexed/commit/923325c48f241c6739aa0f1befb3fbbe20e69ad3), it obviously fixes the deprecation in a simple way.
