### ISSUE TITLE
How does it work with just a few characters in search string?

### ISSUE THREAD

**Issue by szymon33** [dougal/acts_as_indexed#60]
I use in my app:
- Rails 4.2.6
- Postgresql
- acts_as_indexed (0.8.3) with initializer
```
ActsAsIndexed.configure do |config|
  config.min_word_size = 1
end
```
implemented to model ```Product.rb``` by

```acts_as_indexed fields: [:name]```

Assuming the follwoing product name "Uniwersalna pokrywka Stoneline"

The following expression will find the record:
```
Product.with_query('Uniwe')
```
Below expression will NOT find anything. Just one character less though.
```
Product.with_query('Uniw')
```

why?

**Comment by dougal** [comment]
`min_word_size` is meant as a configuration option to prevent abuse. With `min_word_size` set to 1, a query of `U` would match the letter `U` on it's own, but not `Uniwe`.

A prefix query, `^Uniwe`, will match `Uniwersalna` even at the default `min_word_size` of 3.

**Comment by szymon33** [comment]
Thank you very much @dougal for your prompt reply. You are right. But how about searching inside text with search string i. ex. **'sal'** ?

**Comment by dougal** [comment]
No problem.

There is no support for mid-atom matching.

The index is broken up into groups of atoms, in directories by their prefix. It is only efficient to search for either entire atoms, or prefixes.

**Comment by szymon33** [comment]
That is exactly what I need. Thank you and Happy New Year!
